[package]
version = "0.1.0"
name = "bn254-script"
edition = "2021"

[dependencies]
sp1-sdk = { path = "../../../../sp1/crates/sdk" }


[build-dependencies]
sp1-build = { path = "../../../../sp1/crates/build" }
