[workspace]
[package]
version = "0.1.0"
name = "add-program"
edition = "2021"

[dependencies]
# sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", branch = "main" }
sp1-zkvm = { path = "../../../zkvm/entrypoint" }
